101 decoupled action spaces
f1tenth/f1tenth_gym pull request #102
Opened 2023-12-19 22:00 UTC by AhmadAmine998

2023-12-26 06:54 UTC, hzheng40 requested changes

2023-12-26 06:54 UTC, hzheng40 commented on gym/f110_gym/envs/action.py
> +        self._type = "speed"
typo? also should add steering so it's specified

2023-12-26 06:54 UTC, hzheng40 commented on gym/f110_gym/envs/action.py
> +        self._type = "speed"
add steering so it's specified

2023-12-26 06:54 UTC, hzheng40 commented on gym/f110_gym/envs/action.py
> +        if action == "angle":
again, should specifiy steering_angle and steering_speed, just to be less confusing

2023-12-26 20:02 UTC, hzheng40 commented
@AhmadAmine998 I pulled in the updated tests and it's failing right now. You'll probably have to update the tests to use the decoupled action spaces.
Also, should maybe consider handling when only one action type is set, (throw a warning and setting the other to default).

2023-12-26 23:45 UTC, AhmadAmine998 commented
> @AhmadAmine998 I pulled in the updated tests and it's failing right now. You'll probably have to update the tests to use the decoupled action spaces. Also, should maybe consider handling when only one action type is set, (throw a warning and setting the other to default).

I updated the initialization of the action space to be compatible with specifying only one control input as a string. The old tests passed and I now updated the tests to use the decoupled action specification. This way it is compatible with legacy code while still having updated tests

2023-12-27 01:06 UTC, hzheng40 approved these changes
Looks good.

2023-12-27 01:06 UTC, merged