Added waypoint visualization to rendering.py for path planning
f1tenth/f1tenth_gym pull request #25
Opened 2021-02-28 20:59 UTC by wesleyyee1996

Added waypoint visualization to rendering.py for path planning

Modified: rendering.py, f110_env.py

2021-03-02 07:44 UTC, BDEvan5 commented
This looks like a very useful feature, thank you very much.

2021-03-02 20:11 UTC, hzheng40 requested changes
I would leave the f110_env.py file unchanged. It's unnecessary for the waypoints to go through that file. The rendering of waypoints should be more of a util function of rendering.py.
By default, render() of f110_env should not render the waypoints. And it should be up to the users to call something other than env.render() to render the waypoints.

2021-03-02 20:15 UTC, hzheng40 requested changes

2021-03-02 20:15 UTC, hzheng40 commented on gym/f110_gym/envs/rendering.py
> +        # automatically set correct config
The old default shouldn't be deleted. Should probably be a try-except here.

2021-03-02 20:15 UTC, hzheng40 commented on gym/f110_gym/envs/rendering.py
> +        orig_path = [0.]*20
The number of points should probably be an argument of the function

2021-03-02 20:15 UTC, hzheng40 commented on gym/f110_gym/envs/rendering.py
> +                    orig_path[i] = 50.*np_path[-2]
Why 50?
Some comments here will be helpful.

2021-03-02 20:15 UTC, hzheng40 commented on gym/f110_gym/envs/rendering.py
> +            path (array): list of waypoints from path planner
What's the shape requirement?

2021-03-04 15:42 UTC, hzheng40 commented on gym/f110_gym/envs/rendering.py
> +                    orig_path[i] = 50.*np_path[-2]
My bad, I remember the 50 now, it was used as a scaling factor for rendering. I'll add the comment myself.

2021-06-18 17:10 UTC, hzheng40 commented
Closing due to inactivity

2021-06-18 17:10 UTC, closed without merging