modularization of observation space
f1tenth/f1tenth_gym pull request #76
Opened 2023-06-22 23:01 UTC by luigiberducci

Addresses #71. 
It keeps compatibility with old observation space and implements dictionary-based observations for "kinematic_state", "dynamic_state" and arbitrary "features"

2023-07-06 14:52 UTC, hzheng40 requested changes
Setting config for observation type should follow the proposed change in #74

2023-07-06 14:52 UTC, hzheng40 commented on gym/f110_gym/envs/f110_env.py
> +        # observation
This should probably follow the new config dict we'll be using.
We'll fix after merging the other pr.

2023-07-08 01:04 UTC, nandantumu commented on gym/f110_gym/envs/base_classes.py
> +            self.agent_scans[i, :] = current_scan
This is a good catch, I would expect this to result in a speedup

2023-07-08 01:07 UTC, nandantumu approved these changes
LGTM

2023-07-08 21:04 UTC, luigiberducci commented
Using the new config dictionary now. 
Example script modified to use `kinematic_state` instead of original observation.

@hzheng40 @nandantumu please check the changes

2023-07-09 01:36 UTC, hzheng40 commented
Looks good, merging.

2023-07-09 01:36 UTC, hzheng40 approved these changes

2023-07-09 01:37 UTC, merged