rendering
f1tenth/f1tenth_gym pull request #92
Opened 2023-09-14 17:12 UTC by luigiberducci

Update rendering with pygame. 

Support render modes "human", "human_fast", "rgb_array", "rgb_array_list".
Provide minimal set of callbacks to render racelines, local paths and points.
Two configurations for human time and faster.

2023-09-15 15:20 UTC, luigiberducci commented
Basic rendering in pygame implemented, removed dependency on pyglet.
Additional features like window centering and colors have been added to the roadmap.

2023-11-24 15:53 UTC, luigiberducci commented
Close #88, #92 and #98.

Integrate comments discussed in previous meetings.
Now support for callbacks, automatic centering view on different agents, and handle mouse-click from users.

I think it is good enough to close it.
@hzheng40 @nandantumu please review.

2023-12-12 19:36 UTC, hzheng40 requested changes
Few minor things, otherwise looks good

2023-12-12 19:36 UTC, hzheng40 commented on examples/waypoint_follow.py
>  from pyglet.gl import GL_POINTS
Should get rid of this import now

2023-12-12 19:36 UTC, hzheng40 commented on examples/video_recording.py
Might need to add moviepy as a dependency. It didn't install for me.

2023-12-12 19:36 UTC, hzheng40 commented on examples/video_recording.py
> +        print(laptime)
Remove printing

2023-12-12 19:36 UTC, hzheng40 commented on examples/video_recording.py
> +from examples.waypoint_follow import PurePursuitPlanner
This import doesn't work. could do from waypoing_follow ....

2023-12-12 22:03 UTC, nandantumu commented on examples/video_recording.py
agree, I think we need moviepy

2023-12-14 18:40 UTC, nandantumu requested changes

2023-12-14 18:40 UTC, nandantumu commented on gym/f110_gym/envs/rendering/objects.py
This could be refactored to be much simpler:
```python
class TextObject:
    def __init__(self, window_shape, relative_font_size:int = 32, font_name:str = "Arial"):
     ... init stuff is all identical ...

    def _position_resolver(self, position: Union[str, tuple], text, display):
    """ This function takes strings like "bottom center" and converts them into a location for the text to be displayed.
         if position is tuple, then passthrough.
    """

    def render(self, text:str, position, display):
    self.text = self.font.render(...)
    position = self._position_resolver(...)
    display.blit(self.text, position)
```

Then everything is a simple wrapper around this class, and it should be easier for users to reuse this for custom text.

2023-12-14 18:40 UTC, nandantumu commented on setup.py
I think we need to add moviepy

2023-12-14 19:10 UTC, nandantumu commented
I'm also noticing that as I zoom in with rendering.yaml, the render speed gets slower? Not sure what's causing this under the hood

2023-12-15 15:32 UTC, luigiberducci commented on examples/video_recording.py
probably we dont want it as dependency... try catch in `video_recording.py`?

2023-12-15 15:33 UTC, luigiberducci commented on setup.py
as discussed above.

2023-12-15 15:41 UTC, luigiberducci commented on gym/f110_gym/envs/rendering/objects.py
Fine for me, please proceed

2023-12-15 15:42 UTC, luigiberducci commented
> I'm also noticing that as I zoom in with rendering.yaml, the render speed gets slower? Not sure what's causing this under the hood

Known issue due to the way the track surface is rendered. As discussed, we let alternative solutions for future work.

2023-12-19 21:47 UTC, luigiberducci commented
> @hzheng40 @nandantumu the minor required changes done.
> 
> As soon as the change to TextObject (@nandantumu) is done, we can merge.

Implemented TextObject. Merging.

2023-12-19 21:52 UTC, nandantumu approved these changes

2023-12-19 21:52 UTC, merged